### ISSUE TITLE
Chair installation instructions

### ISSUE THREAD

**Issue by zachzeid** [steiza/open_source_furniture#1]
Missing README.md on installation, include wood type, thickness, and how-to put together parts.

**Comment by steiza** [comment]
There's [README.rst](https://github.com/steiza/open_source_furniture/blob/master/README.rst); this was before Markdown won the markup wars.

For wood type I'd recommend a hardwood (I'm using red oak), but there's several options there.

For wood thickness there are some [parameters in the code](https://github.com/steiza/open_source_furniture/blob/master/kitchen_chair.scad#L7-L9), but the depth of cut would come from the CAM step. This is more focused on the CAD step.

How to put together the parts would be after the "Cut" step! Again, this project is more focused on the CAD step.

Thanks for your questions!
